### PR TITLE
Added support for basic auth, per platform

### LINKED ISSUE #187: Add configurable basic authentication
MVP: It should be possible to enable basic authentication for an extender instance.

Bonus: It should be configurable on a per user and per platform level

* user x has access to platform A but not B, C and D
* user y has access to platform B but not A, C and D
* user z has access to platforms A, B, C and D

### PR DESCRIPTION
**Pull request by britzl**
Fixes #187

### CODE REVIEW

**Review by JCash — APPROVED** [review]
Looks good!

**Comment by britzl** [comment]
Going to add a test or two in IntegrationTest.java

**Comment by britzl** [comment]
> Going to add a test or two in IntegrationTest.java

Added a new set of tests in AuthenticationTest.java

**Review by JCash — APPROVED** [review]
Looks good

**Comment by britzl** [comment]
Merging. Error is "out of diskspace"

**Pull request merged**
